"use client";
import Sidebar from "@/components/Sidebar";
import "./globals.css";
import {
    ResizableHandle,
    ResizablePanel,
    ResizablePanelGroup,
} from "@/components/ui/resizable";
import NavBar from "@/components/NavBar";
import Sidebar_Exp from "@/components/Sidebar_Exp";
import { useState } from "react";

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
    const [sidebar_Exp, setSidebar] = useState("");
    return (
        <html lang="en">
            <body className="dark flex flex-col h-screen transition-all">
                <NavBar />
                <ResizablePanelGroup
                    direction="horizontal"
                    className=" w-full rounded-lg border-t"
                >
                    {/* Fixed Sidebar */}
                    <Sidebar onchange={setSidebar} />
                    {/* Sidebar Expanded  */}
                    {sidebar_Exp ? (
                        <ResizablePanel
                            defaultSize={15}
                            minSize={0}
                            maxSize={25}
                        >
                            {/*  Sidebar Expanded */}
                            <Sidebar_Exp open_name={sidebar_Exp} />
                        </ResizablePanel>
                    ) : (
                        <></>
                    )}

                    <ResizableHandle />
                    <ResizablePanel defaultSize={75}>
                        {/* Main Center Code Editor */}
                        <div className="h-full">{children}</div>
                    </ResizablePanel>
                    <ResizableHandle />
                    {/* <ResizablePanel defaultSize={5}>
                        Log Area Right most 
                        <div className="flex h-full items-center justify-center p-6">
                            <h1>Logs</h1>
                        </div>
                    </ResizablePanel> */}
                </ResizablePanelGroup>
            </body>
        </html>
    );
}
